"""Physical-layer channel simulator.

Model
-----
A tapped-delay-line (TDL) multipath channel with the normalised delay/power
profiles of 3GPP TR 38.901 (TDL-A/B/C).  Each tap is a Rayleigh process
generated by a sum-of-sinusoids (Jakes/Clarke) generator with uniform
angle-of-arrival, so the temporal autocorrelation of every tap follows
``J_0(2*pi*f_d*dt)`` and the coherence time is ``0.423/f_d``.

The channel frequency response (CFR) seen at OFDM subcarrier ``f`` and time
``t`` is

    H(t, f) = sum_l a_l(t) * exp(-j*2*pi*f*tau_l).

Reciprocity and its imperfections
---------------------------------
Uplink and downlink share the *same* propagation realisation ``H(t,f)``
(TDD reciprocity), but the two nodes do not observe it identically:

1.  each node adds independent receiver noise at its own SNR;
2.  each node has a static transceiver gain error (scalar + per-subcarrier),
    modelling imperfect RF calibration;
3.  the two soundings are separated by ``tdd_gap_us``, so the channel has
    aged by that amount between the two observations.

Eavesdropper
------------
Eve observes a spatially correlated version of the legitimate CFR,
``H_E = rho*H + sqrt(1-rho^2)*H_ind``, where ``H_ind`` is an independent
realisation of the same TDL profile.  ``rho -> 1`` models an eavesdropper
inside the coherence volume of the legitimate link (worst case).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

import numpy as np

from .config import PhyConfig

# --- 3GPP TR 38.901 TDL profiles: (normalised delay, relative power dB) ---

TDL_PROFILES: Dict[str, tuple[np.ndarray, np.ndarray]] = {
    "TDL-A": (
        np.array([0.0000, 0.3819, 0.4025, 0.5868, 0.4610, 0.5375, 0.6708,
                  0.5750, 0.7618, 1.5375, 1.8978, 2.2242, 2.1718, 2.4942,
                  2.5119, 3.0582, 4.0810, 4.4579, 4.5695, 4.7966, 5.0066,
                  5.3043, 9.6586]),
        np.array([-13.4, 0.0, -2.2, -4.0, -6.0, -8.2, -9.9, -10.5, -7.5,
                  -15.9, -6.6, -16.7, -12.4, -15.2, -10.8, -11.3, -12.7,
                  -16.2, -18.3, -18.9, -16.6, -19.9, -29.7]),
    ),
    "TDL-B": (
        np.array([0.0000, 0.1072, 0.2155, 0.2095, 0.2870, 0.2986, 0.3752,
                  0.5055, 0.3681, 0.3697, 0.5700, 0.5283, 1.1021, 1.2756,
                  1.5474, 1.7842, 2.0169, 2.8294, 3.0219, 3.6187, 4.1067,
                  4.2790, 4.7834]),
        np.array([0.0, -2.2, -4.0, -3.2, -9.8, -1.2, -3.4, -5.2, -7.6,
                  -3.0, -8.9, -9.0, -4.8, -5.7, -7.5, -1.9, -7.6, -12.2,
                  -9.8, -11.4, -14.9, -9.2, -11.3]),
    ),
    "TDL-C": (
        np.array([0.0000, 0.2099, 0.2219, 0.2329, 0.2176, 0.6366, 0.6448,
                  0.6560, 0.6584, 0.7935, 0.8213, 0.9336, 1.2285, 1.3083,
                  2.1704, 2.7105, 4.2589, 4.6003, 5.4902, 5.6077, 6.3065,
                  6.6374, 7.0427, 8.6523]),
        np.array([-4.4, -1.2, -3.5, -5.2, -2.5, 0.0, -2.2, -3.9, -7.4,
                  -7.1, -10.7, -11.1, -5.1, -6.8, -8.7, -13.2, -13.9,
                  -13.9, -15.8, -17.1, -16.0, -15.7, -21.6, -22.8]),
    ),
    "FLAT": (np.array([0.0]), np.array([0.0])),
}


class TDLChannel:
    """One Rayleigh TDL propagation realisation, evaluable at any (t, f)."""

    def __init__(self, cfg: PhyConfig, rng: np.random.Generator,
                 profile: Optional[str] = None) -> None:
        name = profile or cfg.tdl_profile
        norm_delay, power_db = TDL_PROFILES[name]
        self.tau_s = norm_delay * cfg.delay_spread_ns * 1e-9
        p_lin = 10.0 ** (power_db / 10.0)
        self.p_lin = p_lin / p_lin.sum()          # unit total power
        self.n_taps = len(self.tau_s)
        self.fd_hz = cfg.doppler_hz()
        m = cfg.n_sinusoids
        # sum-of-sinusoids parameters: uniform AoA + uniform phase per tap
        self.aoa = rng.uniform(-np.pi, np.pi, size=(self.n_taps, m))
        self.phase = rng.uniform(-np.pi, np.pi, size=(self.n_taps, m))
        self.m = m

    def tap_gains(self, t_s: np.ndarray) -> np.ndarray:
        """Complex tap gains, shape ``(len(t), n_taps)``."""
        t = np.asarray(t_s, dtype=float)[:, None, None]                # (T,1,1)
        arg = 2.0 * np.pi * self.fd_hz * t * np.cos(self.aoa)[None] + self.phase[None]
        # (T, L, M) -> normalised complex Gaussian per tap
        g = np.exp(1j * arg).sum(axis=2) / np.sqrt(self.m)
        return g * np.sqrt(self.p_lin)[None, :]

    def cfr(self, t_s: np.ndarray, f_hz: np.ndarray) -> np.ndarray:
        """Channel frequency response, shape ``(len(t), len(f))``."""
        g = self.tap_gains(t_s)                                        # (T,L)
        steer = np.exp(-2j * np.pi * np.asarray(f_hz)[:, None] * self.tau_s[None, :])
        return g @ steer.T                                             # (T,F)


@dataclass
class Transceiver:
    """Static hardware imperfections of one radio front-end."""

    gain_lin: float
    per_sc_gain_lin: np.ndarray
    snr_db: float

    @staticmethod
    def sample(cfg: PhyConfig, n_pilots: int, rng: np.random.Generator,
               snr_db: Optional[float] = None) -> "Transceiver":
        g_db = rng.normal(0.0, cfg.gain_mismatch_db)
        sc_db = rng.normal(0.0, cfg.freq_mismatch_db, size=n_pilots)
        return Transceiver(10.0 ** (g_db / 20.0), 10.0 ** (sc_db / 20.0),
                           cfg.snr_db if snr_db is None else snr_db)


class RadioWorld:
    """The shared radio environment for one session (UE, gNB and Eve)."""

    def __init__(self, cfg: PhyConfig, seed: Optional[int] = None,
                 rng: Optional[np.random.Generator] = None) -> None:
        self.cfg = cfg
        self.rng = rng if rng is not None else np.random.default_rng(seed)
        # legitimate reciprocal propagation channel + an independent one for Eve
        self.ch = TDLChannel(cfg, self.rng)
        self.ch_eve = TDLChannel(cfg, self.rng)
        self._tx: Dict[str, Transceiver] = {}

    def transceiver(self, role: str, n_pilots: int) -> Transceiver:
        if role not in self._tx:
            snr = self.cfg.eve_snr_db if role == "E" else self.cfg.snr_db
            self._tx[role] = Transceiver.sample(self.cfg, n_pilots, self.rng, snr)
        return self._tx[role]

    def observe(self, role: str, t_s: np.ndarray, f_hz: np.ndarray) -> np.ndarray:
        """Noisy CFR measurement of ``role`` in {'U', 'B', 'E'}."""
        n_pilots = len(f_hz)
        tx = self.transceiver(role, n_pilots)
        h = self.ch.cfr(t_s, f_hz)
        if role == "E":
            rho = float(np.clip(self.cfg.eve_csi_correlation, 0.0, 1.0))
            h = rho * h + np.sqrt(max(0.0, 1.0 - rho ** 2)) * self.ch_eve.cfr(t_s, f_hz)
        h = h * tx.gain_lin * tx.per_sc_gain_lin[None, :]
        # additive receiver noise at the node's operating SNR
        sigma2 = float(np.mean(np.abs(h) ** 2)) / (10.0 ** (tx.snr_db / 10.0))
        noise = np.sqrt(sigma2 / 2.0) * (self.rng.standard_normal(h.shape)
                                         + 1j * self.rng.standard_normal(h.shape))
        return h + noise

    def noise_floor(self, role: str, n_pilots: int) -> float:
        """Noise variance the node knows from its own AGC/thermal calibration."""
        tx = self.transceiver(role, n_pilots)
        return 10.0 ** (-tx.snr_db / 10.0)
